apiVersion: v1
kind: Service
metadata:
  name: storer-service
spec:
  selector:
    app: storer
  ports:
  - protocol: "TCP"
    port: 2500
    nodePort: 30500
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storer
spec:
  selector:
    matchLabels:
      app: storer
  replicas: 2
  template:
    metadata:
      labels:
        app: storer
    spec:
      containers:
      - name: storer
        image: storer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2500
        env:
          - name: MICROSERVICE
            value: "storer"
          - name: PORT
            value: "2500"