# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_task.proto',
  package='task',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftest_task.proto\x12\x04task\"l\n\x05Order\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.task.Order.OrderType\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x01\"\x1d\n\tOrderType\x12\x07\n\x03\x41SK\x10\x00\x12\x07\n\x03\x42ID\x10\x01\"K\n\x15\x43onvertAndSaveRequest\x12\x1f\n\norder_book\x18\x01 \x03(\x0b\x32\x0b.task.Order\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\",\n\x16\x43onvertAndSaveResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\"J\n\x14SaveOrderBookRequest\x12\x1f\n\norder_book\x18\x01 \x03(\x0b\x32\x0b.task.Order\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"+\n\x15SaveOrderBookResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\"8\n\x14SaveFairPriceRequest\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"+\n\x15SaveFairPriceResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x32X\n\tConverter\x12K\n\x0e\x43onvertAndSave\x12\x1b.task.ConvertAndSaveRequest\x1a\x1c.task.ConvertAndSaveResponse2\x9c\x01\n\x06Storer\x12H\n\rSaveOrderBook\x12\x1a.task.SaveOrderBookRequest\x1a\x1b.task.SaveOrderBookResponse\x12H\n\rSaveFairPrice\x12\x1a.task.SaveFairPriceRequest\x1a\x1b.task.SaveFairPriceResponseb\x06proto3'
)



_ORDER_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='task.Order.OrderType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ASK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_ORDER_ORDERTYPE)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='task.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='task.Order.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='task.Order.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='task.Order.quantity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDER_ORDERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=133,
)


_CONVERTANDSAVEREQUEST = _descriptor.Descriptor(
  name='ConvertAndSaveRequest',
  full_name='task.ConvertAndSaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_book', full_name='task.ConvertAndSaveRequest.order_book', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='task.ConvertAndSaveRequest.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=210,
)


_CONVERTANDSAVERESPONSE = _descriptor.Descriptor(
  name='ConvertAndSaveResponse',
  full_name='task.ConvertAndSaveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_success', full_name='task.ConvertAndSaveResponse.is_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=256,
)


_SAVEORDERBOOKREQUEST = _descriptor.Descriptor(
  name='SaveOrderBookRequest',
  full_name='task.SaveOrderBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_book', full_name='task.SaveOrderBookRequest.order_book', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='task.SaveOrderBookRequest.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=332,
)


_SAVEORDERBOOKRESPONSE = _descriptor.Descriptor(
  name='SaveOrderBookResponse',
  full_name='task.SaveOrderBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_success', full_name='task.SaveOrderBookResponse.is_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=377,
)


_SAVEFAIRPRICEREQUEST = _descriptor.Descriptor(
  name='SaveFairPriceRequest',
  full_name='task.SaveFairPriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='task.SaveFairPriceRequest.price', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='task.SaveFairPriceRequest.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=435,
)


_SAVEFAIRPRICERESPONSE = _descriptor.Descriptor(
  name='SaveFairPriceResponse',
  full_name='task.SaveFairPriceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_success', full_name='task.SaveFairPriceResponse.is_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=480,
)

_ORDER.fields_by_name['type'].enum_type = _ORDER_ORDERTYPE
_ORDER_ORDERTYPE.containing_type = _ORDER
_CONVERTANDSAVEREQUEST.fields_by_name['order_book'].message_type = _ORDER
_SAVEORDERBOOKREQUEST.fields_by_name['order_book'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['ConvertAndSaveRequest'] = _CONVERTANDSAVEREQUEST
DESCRIPTOR.message_types_by_name['ConvertAndSaveResponse'] = _CONVERTANDSAVERESPONSE
DESCRIPTOR.message_types_by_name['SaveOrderBookRequest'] = _SAVEORDERBOOKREQUEST
DESCRIPTOR.message_types_by_name['SaveOrderBookResponse'] = _SAVEORDERBOOKRESPONSE
DESCRIPTOR.message_types_by_name['SaveFairPriceRequest'] = _SAVEFAIRPRICEREQUEST
DESCRIPTOR.message_types_by_name['SaveFairPriceResponse'] = _SAVEFAIRPRICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.Order)
  })
_sym_db.RegisterMessage(Order)

ConvertAndSaveRequest = _reflection.GeneratedProtocolMessageType('ConvertAndSaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTANDSAVEREQUEST,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.ConvertAndSaveRequest)
  })
_sym_db.RegisterMessage(ConvertAndSaveRequest)

ConvertAndSaveResponse = _reflection.GeneratedProtocolMessageType('ConvertAndSaveResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTANDSAVERESPONSE,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.ConvertAndSaveResponse)
  })
_sym_db.RegisterMessage(ConvertAndSaveResponse)

SaveOrderBookRequest = _reflection.GeneratedProtocolMessageType('SaveOrderBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEORDERBOOKREQUEST,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.SaveOrderBookRequest)
  })
_sym_db.RegisterMessage(SaveOrderBookRequest)

SaveOrderBookResponse = _reflection.GeneratedProtocolMessageType('SaveOrderBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVEORDERBOOKRESPONSE,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.SaveOrderBookResponse)
  })
_sym_db.RegisterMessage(SaveOrderBookResponse)

SaveFairPriceRequest = _reflection.GeneratedProtocolMessageType('SaveFairPriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEFAIRPRICEREQUEST,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.SaveFairPriceRequest)
  })
_sym_db.RegisterMessage(SaveFairPriceRequest)

SaveFairPriceResponse = _reflection.GeneratedProtocolMessageType('SaveFairPriceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVEFAIRPRICERESPONSE,
  '__module__' : 'test_task_pb2'
  # @@protoc_insertion_point(class_scope:task.SaveFairPriceResponse)
  })
_sym_db.RegisterMessage(SaveFairPriceResponse)



_CONVERTER = _descriptor.ServiceDescriptor(
  name='Converter',
  full_name='task.Converter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=482,
  serialized_end=570,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertAndSave',
    full_name='task.Converter.ConvertAndSave',
    index=0,
    containing_service=None,
    input_type=_CONVERTANDSAVEREQUEST,
    output_type=_CONVERTANDSAVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERTER)

DESCRIPTOR.services_by_name['Converter'] = _CONVERTER


_STORER = _descriptor.ServiceDescriptor(
  name='Storer',
  full_name='task.Storer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=573,
  serialized_end=729,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveOrderBook',
    full_name='task.Storer.SaveOrderBook',
    index=0,
    containing_service=None,
    input_type=_SAVEORDERBOOKREQUEST,
    output_type=_SAVEORDERBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveFairPrice',
    full_name='task.Storer.SaveFairPrice',
    index=1,
    containing_service=None,
    input_type=_SAVEFAIRPRICEREQUEST,
    output_type=_SAVEFAIRPRICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORER)

DESCRIPTOR.services_by_name['Storer'] = _STORER

# @@protoc_insertion_point(module_scope)
